### PR TITLE
Make ;vc use cache instead of fetching contest list

### PR DESCRIPTION
**Pull request by MetalBall887**
Pls tell if you meant this in issue#122

### CODE REVIEW

**Comment by aneesh2312** [comment]
Yes I meant this

**Comment by krofna** [comment]
@MetalBall887 Instead of fetching from cache, you can just return `cache_master.contest_cache.contests` I guess? @meooow25 that's fine right?

**Comment by meooow25** [comment]
Yes, that's right.

**Comment by krofna** [comment]
solved elsewhere

**Pull request closed without merging**
